abstract: pluggable number object
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Number-Object
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp::Clan: 0
  Class::Component: 0
  Class::Inspector: 0
  String::CamelCase: 0
  UNIVERSAL::require: 0
version: 0.01
