---
abstract: 'pluggable number object'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya {dot} pl>'
build_requires:
  Test::Base: 0
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.027
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Object
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp::Clan: 0
  Class::Component: 0
  Class::Inspector: 0
  String::CamelCase: 0
  UNIVERSAL::require: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/yappo/p5-Number-Object/issues
  homepage: https://github.com/yappo/p5-Number-Object
  repository: https://github.com/yappo/p5-Number-Object.git
version: 0.03
x_contributors:
  - 'Kazuhiro Osawa <yappo@shibuya.pl>'
